### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by harr1193** [harr1193/MI-449-SS17-741-html-meta-elements-_f2DoK#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://harr1193-kapv98gmwdanx_f2dok.surge.sh/) and meets the following criteria:

- [x] Include a homepage and at least one other page, for your best-selling T-shirt (you can download a T-shirt image [from ThinkGeek](http://www.thinkgeek.com/clothing/t-shirts/))
- [x] A language is specified for the website (it does _not_ have to be in English!)
- [x] A `title` and `meta name="description"` are provided for each page
- [x] Every page includes a link to a `favicon.ico` file with the company logo (you can [create one here](https://www.hipsterlogogenerator.com/) or design one yourself)
- [x] Location information is provided on every page (you can place the store anywhere in the world, as long as there's an existing building there)
- [x] When each page is shared on Facebook and Twitter, a beautiful card is generated (and the [respective](https://developers.facebook.com/tools/debug/sharing/) [validators](https://cards-dev.twitter.com/validator) should return no errors/warnings -- though you can ignore the `Share App ID Missing` warning for Facebook)

**Comment by egillespie** [comment]
You're keeping me on my toes pushing to gh-pages instead of surge. 😜 

The page looks pretty good, I have a couple of recommendations:

### Touch-up geo tags

The `geo.position` attribute should be separated by a semicolon `;` instead of a comma. While you're updating this, could you also add the `ICBM` meta element? It works the other way around: comma instead of semicolon.

### Use relative path for `favicon.ico`

In `best-seller.html` you have a `/` at the front of your `favicon.ico` file. When your files are hosted in a subdirectory (like they are on GitHub Pages) you have to use relative paths to link to files. Remove the `/` and your `favicon.ico` should start appearing on your `best-seller.html` file.

### Pages do not pass Facebook validation (and image does not show on Twitter)

I'm getting this error when I try to validate your page on Facebook:

![image](https://cloud.githubusercontent.com/assets/5572255/24168535/ebd7f14e-0e50-11e7-87ba-70be5bece7dd.png)

Your image is also not showing in the preview on Twitter's validator.

In `meta` elements, you have to use full URLs that include `https://harr1193.github.io/MI-449-SS17-741-html-meta-elements-_f2DoK/` in order for social media sites to know the correct location.

Please update your `og:image` and `og:url` attributes to include the full paths, then double-check that your pages pass validation.

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! :rocket:

**Comment by harr1193** [comment]
Fixed the errors I had with the facebook validator and cleaned up the organization for the pages, the site is hosted on surge now also.

**Comment by egillespie** [comment]
Thanks! Everything looks great, validations are passing, this is good to go! :shipit:
